### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by tfoote**
Start of a readme

@ablasdel for review/extension

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The repo should specify the license - it should probably also be noted on the cheat sheets.

**Comment by ablasdel** [comment]
@dirk-thomas what is the license? It was never explicitly spelled out anywhere. 
Note: the url.sty file I added is in itself "LaTeX Project Public License, version 2 or later."

**Comment by dirk-thomas** [comment]
I would suggest something like `CC BY 4.0`.

**Comment by ablasdel** [comment]
The only dependency beyond the base trusty install is texlive-latex-base.
I'll update your branch so it can be merged.

**Comment by ablasdel** [comment]
I'm a fan of simplicity so @tfoote @dirk-thomas If my edits/rebase of the readme look good I'll merge this in.

**Comment by tfoote** [comment]
lgtm

**Pull request merged**
